import type { Metadata } from 'next'
import './globals.css'
import Recoil from '@/recoil/Recoil'
import localFont from 'next/font/local'

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="kr">
      <body className={`${pretendard.variable} font-pretendard`}>
        <Recoil>{children}</Recoil>
      </body>
    </html>
  )
}
